var locationOptions = {
'Attic':	1,
'Basement':	2,
'Basement (Theater Rm)':  '3',
'Basement  HVAC Rm':	4,
'Basement (exercise room)':	5,
'Basement (finished)':	6,
'Basement (main rm)':	7,
'Basement (Playroom)':	8,
'Basement (unfinished)':	9,
'Basement/Crawlspace':	10,
'Basement Bathroom':	11,
'Basement Bedroom':	12,
'Basement Office':	13,
'Basement Stairwell (top)':	14,
'Bathroom':	15,
'Bathroom (hallway)':	16,
'Bathroom (small, main level)':	17,
'Bathroom (upper level)':	18,
'Bedroom':	19,
'Bedroom  (pink)':	20,
'Bedroom (basement)':	21,
'Bedroom (front up)':	22,
'Bedroom (rear up)':	23,
'Bedroom (upper level)':	24,
'Bonus Room':	25,
'Bonus Room (lower level)':	26,
'Boys Rm':	27,
'Break Rm.':	28,
'Breakfast area':	29,
'Classroom':	30,
'Common area':	31,
'Conference Rm':	32,
'Conference Rm (upstairs)':	33,
'Copy Room':	34,
'Crawlspace':	35,
'Customer Service':	36,
'Den':	37,
'Dining / Living Rm':	38,
'Dining Room':	39,
'Dining Room (large)':	40,
'Dining Room (small)':	41,
'Downstairs':	42,
'Entry':	43,
'Exterior':	44,
'Family Room':	45,
'Finished Attic':	46,
'Finished Basement':	47,
'Foyer':	48,
'Front Office':	49,
'Front Room':	50,
'Garage':	51,
'Guest Bedroom':	52,
'Guest House':	53,
'Hallway':	54,
'Hallway (upstairs)':	55,
'Hallwy Upstairs':	56,
'HVAC Rm':	57,
'Inside':	58,
'Kitchen':	59,
'Kitchen (wall sample)':	60,
'Kitchen / Den':	61,
'Kitchen /Dining Room':	62,
'Ladies Room':	63,
'Landing (upstairs)':	64,
'Large Office':	65,
'Laundry  (interior wall)':	66,
'Laundry Rm':	67,
'Library (office)':	68,
'Living / Dining':	69,
'Living area (downstairs)':	70,
'Living Room':	71,
'Living Room / Kitchen':	72,
'Lobby':	73,
'Main Rm':	74,
'Master Bathroom':	75,
'Master Bedroom':	76,
'Office':	77,
'Outside':	78,
'Reception area':	79,
'Shipping':	80,  
}